import argparse
from pathlib import Path

from generate_sas_token import generate_sas_token


TEMPLATE = """/*
 * Auto-generated by edge-python/generate_arduino_secrets.py
 * Do not commit this file.
 */

#ifndef SECRETS_H
#define SECRETS_H

const char WIFI_SSID[] = "{wifi_ssid}";
const char WIFI_PASSWORD[] = "{wifi_password}";

const char IOT_HUB_HOST[] = "{iothub_host}";
const int IOT_HUB_PORT = 8883;
const char DEVICE_ID[] = "{device_id}";
const char MACHINE_ID[] = "{machine_id}";

const char SAS_TOKEN[] = "{sas_token}";

#endif
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate arduino/secrets.h with IoT Hub SAS token.")
    parser.add_argument("--iothub-host", required=True, help="IoT Hub host, e.g. iothub-name.azure-devices.net")
    parser.add_argument("--device-id", default="iotdev-0000")
    parser.add_argument("--machine-id", default="MC-0000")
    parser.add_argument("--device-key", required=True, help="IoT Hub device primary key")
    parser.add_argument("--wifi-ssid", required=True)
    parser.add_argument("--wifi-password", required=True)
    parser.add_argument("--ttl-seconds", type=int, default=28800, help="SAS TTL in seconds (default 8 hours)")
    parser.add_argument(
        "--output-file",
        default="../arduino/secrets.h",
        help="Output secrets file path (default ../arduino/secrets.h)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    resource_uri = f"{args.iothub_host}/devices/{args.device_id}"
    sas_token = generate_sas_token(resource_uri, args.device_key, args.ttl_seconds)
    content = TEMPLATE.format(
        wifi_ssid=args.wifi_ssid,
        wifi_password=args.wifi_password,
        iothub_host=args.iothub_host,
        device_id=args.device_id,
        machine_id=args.machine_id,
        sas_token=sas_token,
    )
    output = Path(args.output_file)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content)
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
